print("""choose A for efficiency of otto cycle 
choose B for efficiency of diesel cycle 
choose C for efficiency of dual cycle """)

SELECT = input (" choose from A to C : ")
if SELECT == "A":
    Vmin = float(input("enter Vmin : "))
    Vmax = float(input("enter Vmax : "))
    r =float( Vmax/Vmin)
    print("The compression ratio of otto cycle : " ,r)
    gamma =float( 1.4)
    efficiency = 1 - (1/r**(gamma - 1))
    print("The efficiency of otto cycle for air : " ,efficiency)
elif SELECT == "B" :
    V_min = float(input("enter V_min : "))
    V_max = float(input("enter V_max : "))
    V_expansion = float(input("enter V_expansion : "))
    p =float( V_max/V_min)
    r =float( V_expansion/V_min)
    print("The compression ratio of diesel cycle : " ,r)
    print("The cut off ratio : " ,p)
    gamma =float( 1.4)
    efficiency = 1 - (1/r**(gamma - 1))*(p**(gamma - 1)/gamma*(p-1))
    print("The efficiency of diesel cycle : " ,efficiency)
elif SELECT == "C" :
    V_min = float(input("enter V_min : "))
    V_max = float(input("enter V_max : "))
    V_cutoff = float(input("enter V_cutoff : "))
    P_initial =float(input("enter P_initial : "))
    P_final =float(input("enter P_final : "))
    r = float(V_cutoff/V_min)
    p = float(V_max/V_min)
    a = float(P_initial/P_final)
    print("The compression ratio of dual cycle : " ,r)
    print("The cut off ratio of dual cycle : " ,p)
    print("The pressure ratio or expansion ratio of dual cycle : " ,a)
    gamma =float( 1.4)
    efficiency = 1-(1/r**(gamma - 1))*(a*(p**(gamma - 1))/(a-1)+(a*gamma*(p-1)))
    print("The efficiency of dual cycle : " ,efficiency)
